In [58]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
# from mlxtend.frequent_patterns import apriori, association_rules

In [6]:
df= pd.read_csv('/content/drive/MyDrive/KT ML Internship/Machine Learning/Association Rule Learning/Apriori Algorithm/Market_Basket_Optimisation.csv', header=None)

In [7]:
df

                 0                  1   ...       18         19
0            shrimp            almonds  ...  spinach  olive oil
1           burgers          meatballs  ...      NaN        NaN
2           chutney                NaN  ...      NaN        NaN
3            turkey            avocado  ...      NaN        NaN
4     mineral water               milk  ...      NaN        NaN
...             ...                ...  ...      ...        ...
7496         butter         light mayo  ...      NaN        NaN
7497        burgers  frozen vegetables  ...      NaN        NaN
7498        chicken                NaN  ...      NaN        NaN
7499       escalope          green tea  ...      NaN        NaN
7500           eggs    frozen smoothie  ...      NaN        NaN

[7501 rows x 20 columns]

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7501 entries, 0 to 7500
Data columns (total 20 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       7501 non-null   object
 1   1       5747 non-null   object
 2   2       4389 non-null   object
 3   3       3345 non-null   object
 4   4       2529 non-null   object
 5   5       1864 non-null   object
 6   6       1369 non-null   object
 7   7       981 non-null    object
 8   8       654 non-null    object
 9   9       395 non-null    object
 10  10      256 non-null    object
 11  11      154 non-null    object
 12  12      87 non-null     object
 13  13      47 non-null     object
 14  14      25 non-null     object
 15  15      8 non-null      object
 16  16      4 non-null      object
 17  17      4 non-null      object
 18  18      3 non-null      object
 19  19      1 non-null      object
dtypes: object(20)
memory usage: 1.1+ MB

In [9]:
transactions= []
for i in range(0,7051):
  transactions.append([str(df.values[i,j]) for j in range(0,20) ])

In [49]:
transactions[:][0]

['shrimp',
 'almonds',
 'avocado',
 'vegetables mix',
 'green grapes',
 'whole weat flour',
 'yams',
 'cottage cheese',
 'energy drink',
 'tomato juice',
 'low fat yogurt',
 'green tea',
 'honey',
 'salad',
 'mineral water',
 'salmon',
 'antioxydant juice',
 'frozen smoothie',
 'spinach',
 'olive oil']

In [66]:
!pip install apyori

Collecting apyori
  Downloading apyori-1.1.2.tar.gz (8.6 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: apyori
  Building wheel for apyori (setup.py) ... done
  Created wheel for apyori: filename=apyori-1.1.2-py3-none-any.whl size=5954 sha256=bde4ab64350e3baad344880dfa2c6dfa16a0a305e0501774a87424e1736e182c
  Stored in directory: /root/.cache/pip/wheels/7f/49/e3/42c73b19a264de37129fadaa0c52f26cf50e87de08fb9804af
Successfully built apyori
Installing collected packages: apyori
Successfully installed apyori-1.1.2

In [112]:
from apyori import apriori
rules= apriori(transactions, min_support=0.003, min_confidence=0.2, min_lift=3, min_length=2, max_lenght=2)

In [113]:
results= list(rules)

In [114]:
results[0]

RelationRecord(items=frozenset({'burgers', 'almonds'}), support=0.005531130336122536, ordered_statistics=[OrderedStatistic(items_base=frozenset({'almonds'}), items_add=frozenset({'burgers'}), confidence=0.2671232876712329, lift=3.102942835864684)])

In [115]:
results[2][0]

frozenset({'escalope', 'mushroom cream sauce'})

In [116]:
def inspect(results):
    lhs         = [tuple(result[2][0][0])[0] for result in results]
    rhs         = [tuple(result[2][0][1])[0] for result in results]
    supports    = [result[1] for result in results]
    confidences = [result[2][0][2] for result in results]
    lifts       = [result[2][0][3] for result in results]
    return list(zip(lhs, rhs, supports, confidences, lifts))
suggestions = pd.DataFrame(inspect(results), columns = ['Left Hand Side', 'Right Hand Side', 'Support', 'Confidence', 'Lift'])

In [117]:
suggestions.sort_values(by='Lift')

        Left Hand Side Right Hand Side   Support  Confidence      Lift
29              shrimp            milk  0.003971    0.388889  3.006640
95              shrimp             nan  0.003971    0.388889  3.006640
41           spaghetti          shrimp  0.006240    0.217822  3.011493
55              pepper       spaghetti  0.003404    0.533333  3.013248
130             pepper       spaghetti  0.003404    0.533333  3.013248
..                 ...             ...       ...         ...       ...
141      mineral water             nan  0.003687    0.382353  5.797786
159          olive oil             nan  0.003404    0.289157  5.961530
104          olive oil            milk  0.003404    0.289157  5.961530
105  frozen vegetables            milk  0.003262    0.403509  8.319124
160  frozen vegetables             nan  0.003262    0.403509  8.319124

[170 rows x 5 columns]